name: Run Jest tests

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  FORCE_COLOR: 2
jobs:
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
          - 18
          - 16
          - 14
    name: Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Verify Node dependency cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: node-dependencies-
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
